#!/usr/bin/env python3
"""
Huginn theme switcher.
Applies a named theme across Quickshell, Kitty, Niri, and Vim.
Usage: theme.py <midnight|obsidian|ember|verdant>
"""
import json
import re
import subprocess
import sys
from pathlib import Path

DOTFILES   = Path.home() / "dotfiles"
THEMES_DIR = Path(__file__).parent.parent / "themes"
CONFIG_DIR = Path.home() / ".config" / "huginn"
CURRENT_THEME_FILE = CONFIG_DIR / "current-theme.json"


def load_theme(slug: str) -> dict:
    path = THEMES_DIR / f"{slug}.json"
    if not path.exists():
        available = [p.stem for p in THEMES_DIR.glob("*.json")]
        raise SystemExit(f"Unknown theme '{slug}'. Available: {', '.join(available)}")
    with open(path) as f:
        return json.load(f)


def apply_theme(slug: str) -> None:
    theme = load_theme(slug)
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    # Write single-line JSON — QML SplitParser reads line-by-line
    CURRENT_THEME_FILE.write_text(json.dumps(theme))

    apply_kitty(theme)
    apply_niri(theme)
    apply_vim(theme)

    print(f"ᚱ Theme switched: {theme['name']}")


def apply_kitty(theme: dict) -> None:
    kitty_dir = Path.home() / ".config" / "kitty"
    kitty_dir.mkdir(parents=True, exist_ok=True)
    theme_file = kitty_dir / "huginn-theme.conf"

    theme_file.write_text(f"""\
# Huginn Theme: {theme['name']} — generated by huginn-theme, do not edit manually
foreground        {theme['text_secondary']}
background        {theme['bg']}
color0            {theme['muted']}
color8            {theme['muted']}
color1            {theme['red']}
color9            {theme['red']}
color2            {theme['green']}
color10           {theme['green']}
color3            {theme['yellow']}
color11           {theme['yellow']}
color4            {theme['accent']}
color12           {theme['accent']}
color5            {theme['purple']}
color13           {theme['purple']}
color6            {theme['cyan']}
color14           {theme['cyan']}
color7            {theme['text_primary']}
color15           {theme['text_primary']}
cursor            {theme['text_primary']}
cursor_text_color {theme['bg']}
selection_background  {theme['surface']}
selection_foreground  none
url_color             {theme['accent']}
active_border_color   {theme['accent']}
inactive_border_color {theme['muted']}
bell_border_color     {theme['gold']}
active_tab_foreground   {theme['accent']}
active_tab_background   {theme['surface']}
inactive_tab_foreground {theme['text_secondary']}
inactive_tab_background {theme['bg']}
tab_bar_background      {theme['bg']}
""")

    # Live-reload all kitty instances
    try:
        subprocess.run(
            ["kitten", "@", "set-colors", "--all", "--configured", str(theme_file)],
            capture_output=True, timeout=5,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass


def apply_niri(theme: dict) -> None:
    niri_config = DOTFILES / "niri" / "config.kdl"
    if not niri_config.exists():
        return

    content = niri_config.read_text()
    content = re.sub(
        r'(active-gradient from=")[^"]*(" to=")[^"]*(")',
        rf'\g<1>{theme["niri_focus_from"]}\g<2>{theme["niri_focus_to"]}\g<3>',
        content,
    )
    niri_config.write_text(content)

    try:
        subprocess.run(["niri", "msg", "action", "reload-config"],
                       capture_output=True, timeout=5)
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass


def apply_vim(theme: dict) -> None:
    vim_theme = CONFIG_DIR / "huginn-theme.vim"
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    vim_theme.write_text(f"""\
" Huginn Theme: {theme['name']} — generated by huginn-theme, do not edit manually
if has('termguicolors')
  let g:terminal_color_4  = '{theme['accent']}'
  let g:terminal_color_12 = '{theme['accent']}'
  hi CursorLine  guibg={theme['surface']}
  hi Visual      guibg={theme['surface']}
  hi StatusLine  guifg={theme['accent']} guibg={theme['surface']} gui=bold
  hi VertSplit   guifg={theme['muted']}
  hi LineNr      guifg={theme['muted']}
  hi Search      guibg={theme['accent']} guifg={theme['bg']}
  hi IncSearch   guibg={theme['gold']}   guifg={theme['bg']}
endif
""")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: theme.py <midnight|obsidian|ember|verdant>")
        sys.exit(1)
    apply_theme(sys.argv[1])
